version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary tools...
  pre_build:
    commands:
      - echo Preparing for build...
  build:
    commands:
      - echo Packaging source files into build.zip...
      - zip -r build.zip ./*
  post_build:
    commands:
      - echo Build process completed!
artifacts:
  files:
    - build.zip
  discard-paths: yes
